global:
  scrape_interval: 5s # Check for new data every 5 seconds

scrape_configs:
  - job_name: 'chat2carpool_app'
    static_configs:
      # host.docker.internal allows Docker to see your host (Windows/WSL) network
      # Port 8000 matches what we set in init_metrics()
      - targets: ['192.168.3.112:8000']